### ISSUE TITLE
Liveness probe for netbox

### ISSUE THREAD

**Issue by florianschendel** [netbox-community/netbox-chart#100]
Hi Chris,

a liveness probe to restart the pod would be very helpful for installations.

Best regards
Florian

**Comment by bootc** [comment]
There's currently no URI in NetBox that's really suitable for use with a liveness probe. It looks like https://github.com/netbox-community/netbox/issues/8831 might help with something like that, however.

Learnk8s.io's [Kubernetes production best practices](https://learnk8s.io/production-best-practices) (which I tend to broadly agree with) call for _passive_ liveness checks, so it should really call into the Python code but basically do nothing except return success. The readiness check could/should do a bit more work to be particularly useful, and the liveness and readiness checks should not be the same.

The existing readiness probe just loads the login page. That isn't ideal but it's the closest we've got to something useful in NetBox at the moment.

**Comment by RangerRick** [comment]
Hey, just revisiting old issues. @bootc would the `/api/status` endpoint be good for this? It doesn't do _nothing_ but it does _nearly_ nothing.

```json
curl --silent http://localhost:8080/api/status/ | jq
{
  "django-version": "4.2.6",
  "installed-apps": {
    "debug_toolbar": "4.2.0",
    "django_filters": "23.3",
    "django_prometheus": "2.3.1",
    "django_rq": "2.8.1",
    "django_tables2": "2.6.0",
    "drf_spectacular": "0.26.5",
    "drf_spectacular_sidecar": "2023.10.1",
    "graphene_django": "3.0.0",
    "graphiql_debug_toolbar": "0.2.0",
    "mptt": "0.14.0",
    "rest_framework": "3.14.0",
    "social_django": "5.4.0",
    "taggit": "4.0.0",
    "timezone_field": "6.0.1"
  },
  "netbox-version": "3.6.4",
  "plugins": {},
  "python-version": "3.11.4",
  "rq-workers-running": 1
}
```

**Comment by bootc** [comment]
As long as it _doesn’t_ try to talk to the database or Redis it looks like it would do the trick. Ideally it would also be available without authentication for simplicity.

This blog post describes how liveness and readiness proves work: https://blog.colinbreck.com/kubernetes-liveness-and-readiness-probes-how-to-avoid-shooting-yourself-in-the-foot/

**Comment by LeoColomb** [comment]
As [per the docs](https://demo.netbox.dev/api/schema/swagger-ui/#/status/status_retrieve), this endpoint is "A lightweight read-only endpoint for conveying NetBox's current operational status".
It sounds to match the need pretty well 😊

**Comment by RangerRick** [comment]
Looking closer at the code, it _does_ [call into the worker API among other things](https://github.com/netbox-community/netbox/blob/develop/netbox/netbox/api/views.py#L47) so maybe the `/api/status` bit should be a readiness probe, and we just call `/api` (which literally just returns a list of resources) for readiness.

**Comment by bootc** [comment]
The other thing I thought of is: does this still work if authentication is required?

**Comment by LeoColomb** [comment]
Sane thought, and neither `/api` nor `/api/status` require auth.
They can be tried out directly on the demo NetBox online, without being logged in:
* https://demo.netbox.dev/api/
* https://demo.netbox.dev/api/schema/swagger-ui/#/status/status_retrieve

**Comment by bootc** [comment]
Well, https://netbox.boo.tc/api/ is works without authentication, but https://netbox.boo.tc/api/status/ gives a 403 Forbidden. So I think /api/ would probably work well for a readiness check.

Probably the best place for a liveness check is an extra endpoint within NGINX Unit in the container; and actually it looks like there's [something like that on port 8181](https://github.com/netbox-community/netbox-docker/blob/0c99ff8b5663db3e0db5a45660cebda9f917508b/docker/nginx-unit.json#L9-L14)? In fact in my NetBox I can query `http://${POD_IP}:8081/status/` and get some JSON back from NGINX Unit; that seems like a plausible candidate for a liveness check to me.

**Comment by RangerRick** [comment]
> Well, https://netbox.boo.tc/api/ works without authentication, but https://netbox.boo.tc/api/status/ gives a 403 Forbidden. So I think `/api/` (don't forget the trailing `/`) would probably work well for a readiness check.

Yeah, I think the 403 is new in NetBox 4.0 because of changes in the default security settings, so we can't use that, it seems.
