### ISSUE TITLE
Warning about Readiness probe failed

### ISSUE THREAD

**Issue by Shiftmaj** [netbox-community/netbox-chart#113]
Hi,

I'm getting the following Warning while using this chart:
`Readiness probe failed: Get "http://p.o.d.ip:8080/login/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

The service works just fine. I also tried to reach the pod directly on `/login/` with `curl` and it returns `200 OK`.
Do you have any idea why this Warning is fired up?

Best regards,
Marc-Antoine

**Comment by bandwiches** [comment]
I had a similar log, but after investigating it turned out to be a leftover log from the init phase.  It appears the readiness probe values can be altered and even disabled as of today.

**Comment by LeoColomb** [comment]
Closing as most probably a leftover of the init phase indeed. Should also be improved with #100.
