### ISSUE TITLE
Custom worker

### ISSUE THREAD

**Issue by AlexDaichendt** [netbox-community/netbox-chart#130]
Hey, 

how would I go about adding a custom worker with this chart? for reference, I updated the axians-netbox-pdu plugin, which requires a worker for collecting the SNMP data from the PDUs, see here https://github.com/minitriga/axians-netbox-plugin-pdu#preparation

as far as I can tell, there is no standardized way to achieve that with this chart. Am I wrong?

**Comment by bootc** [comment]
I'm not sure why the plugin would require its own worker rather than just using the existing queues, but this seems to be a request that has come up a few times. I'll have a think about this for the upcoming 5.x release of the chart.
