### ISSUE TITLE
A general question: Is this repository still actively maintained?

### ISSUE THREAD

**Issue by Delta1977** [netbox-community/netbox-chart#162]
@bootc:  Is this repository still actively maintained? somehow the charts are only for netbox 3.4. Currently 3.5 is active and 3.6 is just around the corner. There is also not much happening on the part of the maintainer with the open issues.
Can you please give us a feedback

Thank You

**Comment by bootc** [comment]
I mean I'm not dead, but I haven't had time to do any active maintenance for quite some time and I don't expect to for the foreseeable future. The chart works just fine with 3.5, though, just update the image tag.

**Comment by rjhenry** [comment]
Taking a look at the changelogs for 3.6, I can't see anything that would cause an issue, though I haven't tried with the 3.6.x images.

**Comment by inventionlabsSydney** [comment]
@bootc Are you willing to let some other devs on to help keep things current?

**Comment by bootc** [comment]
Yeah I'd love some help to keep things moving along. I'll hopefully have some time in a week or two to get back to things too and maybe onboard people for help, too.

**Comment by rossigee** [comment]
I've been using this chart at home and at work for a while now. I'd be more than happy to help out with a little maintenance and patch review etc.

**Comment by Delta1977** [comment]
Same here, i can help out with a little maintenance and patch review etc too.

**Comment by Atoms** [comment]
Opting into providing maintenance of repo :) don't let die best chart for netbox !

**Comment by Sam6734** [comment]
> Thank you for the quick feed back. I know the trick with the tag for 3.5. Did you think it would work with 3.6?

what is the trick with the tag for 3.5?

**Comment by K4pper** [comment]
> > Thank you for the quick feed back. I know the trick with the tag for 3.5. Did you think it would work with 3.6?
> 
> what is the trick with the tag for 3.5?

Hey @Sam6734
To make Netbox version 3.5 or 3.6 run for that matter you can just edit the image tag in your values file.
So if i wanted to run Netbox version 3.6.4 in my deployment just change your values file to point to the following tag:
``` 
image:
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v3.6.4"

**Comment by bootc** [comment]
Despite my best intentions I have neither the time nor the motivation to maintain this chart. Rather than see it die I'd like to give what I have to the NetBox Community project. If you'd like to see that happen, please participate in this discussion: https://github.com/netbox-community/netbox-docker/discussions/1160

**Comment by bootc** [comment]
Just a quick note that someone from `netbox-community` has reached out to me and plans are being hatched to transfer the repository under https://github.com/netbox-community. The intention is that the chart would be actively maintained, will remain open source (of course), and I'll also remain a maintainer of the project in its new home.

**Comment by bootc** [comment]
The repository has now been transferred! Welcome to netbox-community! 🎉

**Comment by inventionlabsSydney** [comment]
@bootc will you be choosing who the maintainers are? As we probably should have more than just yourself to keep project momentum etc.

**Comment by bootc** [comment]
> @bootc will you be choosing who the maintainers are? As we probably should have more than just yourself to keep project momentum etc.

No, I won't be doing the choosing, and I'm fine with that. At the moment basically anyone would be doing a better job than me at the moment. I can't say just yet what's going on here but I'm looking forward to things being more active.

**Comment by bootc** [comment]
@LeoColomb those are the kind of things that I would have loved to be able to implement for this chart, but never had the time. Honestly at this stage I think it would be great if you could submit PRs for some of those things, and I expect they'd be looked at favourably. I expect it'll be about another week or so before we start seeing much movement from the @netbox-community maintainer(s).

**Comment by LeoColomb** [comment]
> Honestly at this stage I think it would be great if you could submit PRs for some of those things

Sure, the first batch has been submitted 👍 
Quite challenging, though, since it affects more the structure than the actual chart value per se.

**Comment by gagansingh-ops** [comment]
Hi Everyone, I would like to help out as well! I used this project to deploy Nbx on an AKS (Azure Kubernetes Cluster) in a large Enterprise organization. The management is very happy with the results and I would like to give back to the community :)

**Comment by RangerRick** [comment]
Hey all, just popping into this issue to introduce myself. I've just been brought on by NetBox Labs to manage our Docker and Helm packaging (among other things) and I'm going to be working my way through open issues and helping to take over maintainership. Thanks to everyone who has chimed in, and I'll be taking a look at PRs in the coming weeks.

**Comment by bootc** [comment]
Just wanted to say welcome, @RangerRick! NetBox Labs have been working with me on this for a few weeks, as I mentioned above, so hopefully this is the start of a new chapter for this chart. 🎉

**Comment by RangerRick** [comment]
I guess we can close this. @LeoColomb has been brought on as an additional maintainer, and both he and @bootc have been keeping an eye on the project on top of it being my job to keep up with it.

Thanks, everyone, for your patience.
