### ISSUE TITLE
Modify Chart for Netbox Release 3.6.0

### ISSUE THREAD

**Issue by Delta1977** [netbox-community/netbox-chart#164]
Hi, 
Netbox 3.6 was released: https://github.com/netbox-community/netbox-docker/releases/tag/2.7.0

With this release there is a renaming of a few Vars.
I think this is not many work to modify your Chart and release a new Version.

Can you do this?

edit: 3.7 -> 3.6

**Comment by jsenecal** [comment]
NetBox 3.6 was released, not 3.7...

**Comment by remram44** [comment]
Netbox 3.6 also requires postgres >=12

**Comment by jonkerj** [comment]
I just noticed that @bootc seems to be dusting off the chart, bumping postgres, chart version, preparing for 3.6.0 in the development branch. I hope this leads to a release soonish

**Comment by bootc** [comment]
Yeah I hope I get enough round tuits and energy to make a release this weekend. If you want to get your PRs in, now would be a good time to polish them up! :-)

**Comment by TheChef23** [comment]
@bootc let me know if there is anything I can do to help you out and to get everyone closer to a release.

**Comment by jonkerj** [comment]
Hey @bootc, what's the latest on this one?

**Comment by remram44** [comment]
Ok now NetBox 3.7 is out.

This is really awkward, because the author is making changes and responding to issues, but a release is not coming out. Should we fork anyway?

**Comment by RangerRick** [comment]
I'm going to go ahead and close this now that we have some momentum going again. Sorry about the delay, but if you've followed any of the other places talking about this, I've been brought on by NetBox Labs to help take ownership of the charts (with @bootc's blessing and assistance).

The only major technical issue with the 4.1.1 chart and 3.7 that I know of is that the provided PostgreSQL is too old, but if you use your own (or upgrade/migrate the postgresql in the chart) it should still work fine.

Going forward the 5.x charts in `develop` are updated to 4.0 and should still be 3.7-compatible as far as I can tell if you wish to override the image. I'm working to wrap up some final stuff and release a 5.0.0 non-beta in hopefully the next few weeks.

In the meantime, if you'd like to bang on the 5.0 beta charts in the new repo, I'd love feedback about anything that might be missing or needs cleanup. There's been a lot of refactoring going on in the last few weeks.

**Comment by Delta1977** [comment]
Thank you for the great work. Since movement away from bootc I'm on develop branch, but for long time before on old bootc with external Postgres and since a few days on external redis.

**Comment by remram44** [comment]
I'm sorry to be that guy, but there have been 78 beta releases, and they seem to contain nothing but dependency updates. Is there a blocker to GA? Is there a way we can help get out of beta?

**Comment by LeoColomb** [comment]
@remram44 #286
