### ISSUE TITLE
Error while using bundled redis database - similar to #168

### ISSUE THREAD

**Issue by tbotnz** [netbox-community/netbox-chart#170]
When using ArgoCD and performing a sync through a pipeline the second deployment fails due to redis auth errors, if i prune, force & replace from Argo it comes right however not ideal similar to #168.

Going to use redis outside the chart.

Raising incase anyone else runs into this

**Comment by bootc** [comment]
Are you setting the `redis.auth.password` in your chart values? As mentioned in the README, you _must_ set the passwords in the PostgreSQL and Redis sub-charts otherwise each time Helm runs it generates a new random password.

**Comment by Atoms** [comment]
another possibility is to add ignoredifferences key for that password on ArgoCD side and then it will not regenerate it.

**Comment by LeoColomb** [comment]
Closing in favor of #187
