### ISSUE TITLE
LDAP not working (configuration not applied to pod after configuring and pushing helm chart)

### ISSUE THREAD

**Issue by ServiceOfTerms** [netbox-community/netbox-chart#174]
Hi, I am facing an issue with LDAP configuration with latest helm chart. It doesn't seem to pass LDAP environment variables to a pod, and I don't see any LDAP outbound traffic from netbox app. Also, during the boot, no LDAP config is loaded.

I followed your guide from readme

Is there anything I am missing or is it a bug?

**Netbox version:** v3.6.6
**Chart version**: 4.1.1 (latest)

**Comment by LeoColomb** [comment]
Closing as explanation and solution provided.
