### ISSUE TITLE
Missing documentation or support for AzureAD authentication

### ISSUE THREAD

**Issue by jbek7** [netbox-community/netbox-chart#176]
I don't see AzureAD configurations were not documented or is it not supported? Any examples if it's supported?

**Comment by rjhenry** [comment]
Adapt config examples from [the authentication documentation](https://github.com/bootc/netbox-chart/blob/develop/docs/auth.md) with values from [the AzureAD implementation for Python Social Auth](https://python-social-auth.readthedocs.io/en/latest/backends/azuread.html)

**Comment by LeoColomb** [comment]
Closing as documentation already available as linked by @rjhenry.
