### ISSUE TITLE
no new releases after  version 4.1.1

### ISSUE THREAD

**Issue by moerafiee** [netbox-community/netbox-chart#179]
hi there is no release after version 4.1.1 would you please release version 5.0.0 tag?

**Comment by davidusken** [comment]
@moerafiee the future of this chart is currently "discussed" here: https://github.com/netbox-community/netbox-docker/discussions/1160

**Comment by RangerRick** [comment]
new 5.0 chart is under active maintenance, and currently available in beta form at https://charts.netbox.oss.netboxlabs.com/
