### ISSUE TITLE
Value metricsEnabled has no effect

### ISSUE THREAD

**Issue by tgoodsell-tempus** [netbox-community/netbox-chart#196]
`metricsEnabled` has a help text of "Expose Prometheus metrics at the `/metrics` HTTP endpoint".

However, there's nothing in the template to check that value and then stand up the necessary config/port exposure/service exposure for this. Effectively it does nothing, this also feeds into the `serviceMonitor` being non-working.

See: https://github.com/search?q=repo%3Anetbox-community%2Fnetbox-chart%20metricsEnabled&type=code

**Comment by LeoColomb** [comment]
As listed in the search results you liked, there is a reference in the NetBox configuration map:

https://github.com/netbox-community/netbox-chart/blob/9f4b1606cd74519e9e627bb7ad9182672557ff91/charts/netbox/templates/configmap.yaml#L148

This configuration is explained in the official NetBox doc: https://docs.netbox.dev/en/stable/integrations/prometheus-metrics/

Have you tried to reach the endpoint with a Prometheus client?

**Comment by rjhenry** [comment]
I've been using the `values.metricsEnabled` value of `true` and that's been collecting metric data. I haven't tested the `serviceMonitor` since drafting the PR to add it (waiting for a fresh release!) but I can't imagine any reason why it wouldn't work.

Are you aware that the Metrics endpoint is an endpoint under same service and port as the regular web interface?

**Comment by tgoodsell-tempus** [comment]
@LeoColomb @rjhenry Yes you're both correct, I'm wrong in my assumption.

I'd gotten confused by the netbox-docker instructions which show the use of port `8001` for metrics in https://github.com/netbox-community/netbox-docker/wiki/Monitoring, while their standard setup instructions used a port number of `8000`. 

I'd assumed that meant Netbox was setting up the metrics port as an increment of one higher than the standard port.

That was wrong.
