### ISSUE TITLE
Problem with new sorted Values / Podsecuritycontext 

### ISSUE THREAD

**Issue by Delta1977** [netbox-community/netbox-chart#203]
Hi, with the new sorted Values / Template something is wrong:
For apps/Deployment/netbox/netbox-worker and batch/CronJob/netbox/netbox-housekeeping 
Parts of the podsecuritycontext come to Securitycontext :
![image](https://github.com/netbox-community/netbox-chart/assets/1581154/51042cdc-ad85-44d6-940e-8987d565a61c)

For apps/Deployment/netbox/netbox its ok.

same for the subPath Variable

**Comment by LeoColomb** [comment]
Thanks for pointing this out, I'll have a look 👍
