### ISSUE TITLE
IPv6 only compatibility

### ISSUE THREAD

**Issue by fayak** [netbox-community/netbox-chart#205]
Hello !

We're trying to run netbox-chart in an IPv6 only cluster, and apparently netbox doesn't listen on :: but on 0.0.0.0. However, I'm not sure how I can change this behaviour.

Is there a way to do select the IP on which netbox will listen to ?

**Comment by RangerRick** [comment]
Hrm, this is a good question, since looking at the docker image it appears the nginx unit is, in theory, [already configured to listen on both](https://github.com/netbox-community/netbox-docker/blob/release/docker/nginx-unit.json#L6).

My home network is IPv4-only at the moment, so we'll have to find an environment to test on.

**Comment by fayak** [comment]
This file seems a bit different in the image used by the chart : 
```
I have no name!@netbox-56b6f9b58c-mg989:/$ find -name nginx-unit.json
./etc/unit/nginx-unit.json
find: ‘./etc/ssl/private’: Permission denied
find: ‘./proc/tty/driver’: Permission denied
find: ‘./root’: Permission denied
find: ‘./var/cache/apt/archives/partial’: Permission denied
find: ‘./var/cache/ldconfig’: Permission denied
I have no name!@netbox-56b6f9b58c-mg989:/$ cat ./etc/unit/nginx-unit.json
{
  "listeners": {
    "*:8080": {
      "pass": "routes"
    }
  },

  "routes": [
    {
      "match": {
        "uri": "/static/*"
      },
      "action": {
        "share": "/opt/netbox/netbox${uri}"
      }
    },

    {
      "action": {
        "pass": "applications/netbox"
      }
    }
  ],

  "applications": {
    "netbox": {
      "type": "python 3",
      "path": "/opt/netbox/netbox/",
      "module": "netbox.wsgi",
      "home": "/opt/netbox/venv",
      "processes": {
        "max": 4,
        "spare": 1,
        "idle_timeout": 120
      }
    }
  },

  "access_log": "/dev/stdout"
}
```

**Comment by RangerRick** [comment]
Ah, looks like `ALLOWED_HOSTS` can be [set in your values file](https://github.com/netbox-community/netbox-chart/blob/develop/charts/netbox/templates/configmap.yaml#L77)

**Comment by fayak** [comment]
I will try adding this extra 
```
"[::]:8080": {
      "pass": "routes/main"
    },
    ```
    configuration snippet to my existing deployment and let you know.
    Otherwise, if you have some hints or tests you want to run, I can try doing them for you :)

**Comment by RangerRick** [comment]
OH, I just realized you're probably using the 4.1.1 chart, which still points to netbox 3.2.x (although it supports up to 3.5.x, or higher if you use your own postgresql)

So yeah, if you override that file it should work.

**Comment by RangerRick** [comment]
We're currently in beta for the 5.0 release of the chart, if you want to try it you can pull 5.0.0-betaX from https://charts.netbox.oss.netboxlabs.com/

**Comment by fayak** [comment]
You're right ! Adding 
```
image:
    tag: v3.7.8
```
to the values simply solved the issue. Thanks for the details :)

I believe we can close this issue as the solution has been upstreamed, and I guess the 5.0 release of the chart will fix it :+1:

**Comment by RangerRick** [comment]
great news! I'll go ahead and close this then
