### ISSUE TITLE
Netbox new version 5.0.0-beta12 dependency chart issue

### ISSUE THREAD

**Issue by sanjaypjana** [netbox-community/netbox-chart#213]
Trying to use 5.0.0-beta12 but it throws an error at dependency chart for redis. I am running the chart by enabling postgres and redis. 

Error at helm install -> Error: UPGRADE FAILED: parse error at (netbox/charts/redis/charts/common/templates/_resources.tpl:15): unclosed action

**Comment by RangerRick** [comment]
Are you trying to upgrade an already-installed 4.1.1 chart to 5? The 5.0 charts use a newer version of redis and postgres and you probably need to do some pre-upgrade work if you're wanting it to go smoothly. (I have not tested upgrading at all yet, so I don't have specifics to give you.)

**Comment by sanjaypjana** [comment]
Yes, I have already an installed chart of version 4.1.1 and now upgrading it to version 5.0.0-beta12

**Comment by LeoColomb** [comment]
For accurate help to be provided, you're welcome to provide more context regarding this issue.
* What version of Helm are you using?
* How did you perform the chart upgrade?
* Can you provide your values file?

**Comment by sanjaypjana** [comment]
Thanks for your inputs. I am finally able to get the netbox installed with Redis and Postgresql managed externally. The issue i had was on my helm command and had to fix it. Now all workloads are installed, Getting below error on the netbox pod 

[django.db.utils.OperationalError: [Errno -2] Name or service not known]

Below is my values.yaml input. I have postgresql service running on same namespace of name my-postgresql and redis service named my-redis-master on the same namespace as well.

**Comment by bootc** [comment]
Please remove the `http://` from your PostgreSQL and Redis host names, they should just be the bare service names. Assuming they're in the same namespace you'd probably just want `host: my-postgresql` and `host: my-redis-master`, for example.

**Comment by sanjaypjana** [comment]
Thanks, That solved the error. Is there a recommended version of postgresql and redis bitnami charts from artifactory to be used when managing them externally from the netbox community.

**Comment by sanjaypjana** [comment]
I am ok to close the issue since the errors i got are now fixed.
