### ISSUE TITLE
netbox ipv6 listens

### ISSUE THREAD

**Issue by kfox1111** [netbox-community/netbox-chart#220]
We tried to deploy `netbox-5.0.0-beta13` on a cluster that has ipv6 totally disabled. It fails to listen on the [::] rules. Can those be made configurable?

**Comment by RangerRick** [comment]
This is a changed that happened in the upstream docker image. We've had reports of it failing both on IPv6-only clusters _and_ IPv4-only clusters. (sigh 😅)

The good news is that you can update it to work however you want using the [overrideUnitConfig](https://github.com/netbox-community/netbox-chart/blob/develop/charts/netbox/values.yaml#L449) section of `values.yaml`. You can take a look at the [one provided by `netbox-docker`](https://github.com/netbox-community/netbox-docker/blob/release/docker/nginx-unit.json) as reference.

This will probably be a more common problem over time, we should update the docs to talk about it.

**Comment by kfox1111** [comment]
Ah. Perfect. Will give that a try. Thanks! :)

**Comment by kikem4n** [comment]
Having the same issue here. How would be the right way to set it trough a `--set` ? Have tried but I do not get having netbox listen on [::]:8080 :(

**Comment by dbrennand** [comment]
> Having the same issue here. How would be the right way to set it trough a `--set` ? Have tried but I do not get having netbox listen on [::]:8080 :(

@kikem4n Using your own `values.yaml` file.

```yaml
# values.yaml
overrideUnitConfig:
  {
    "listeners": {
      "0.0.0.0:8080": {
        "pass": "routes/main"
      },
      # Remove below lines
      "[::]:8080": {
        "pass": "routes/main"
      },
      "0.0.0.0:8081": {
        "pass": "routes/status"
      },
      # Remove these too
      "[::]:8081": {
        "pass": "routes/status"
      }
    },
    # ... Rest of the config from https://github.com/netbox-community/netbox-docker/blob/release/docker/nginx-unit.json
  }
```

Then provide your `values.yaml` to Helm: 

```bash
helm install netbox oci://ghcr.io/netbox-community/netbox-chart/netbox -f values.yaml
```

**Comment by LeoColomb** [comment]
For your information, this has been documented on the Docker image wiki: https://github.com/netbox-community/netbox-docker/wiki/Troubleshooting#netbox-container-doesnt-start-when-ipv6-is-disabled

With the use of `overrideUnitConfig` in the values, the workaround is fairly simple.
https://github.com/netbox-community/netbox-chart/blob/190868ca133844c63019e5672ea73d773096d25f/charts/netbox/values.yaml#L476-L516

Closing in favor of https://github.com/netbox-community/netbox-docker/issues/997 & https://github.com/netbox-community/netbox-docker/issues/925
