### ISSUE TITLE
Netbox repo link not working?

### ISSUE THREAD

**Issue by TheoBassaw** [netbox-community/netbox-chart#221]
Hi, I was trying to get started with netbox using the chart but for some reason, the link for the chart doesn't work. At least, Flux can't access it, and directly using https://charts.netbox.oss.netboxlabs.com leads to a 404. Is there another url for the repo?

**Comment by RangerRick** [comment]
GitHub Pages gives a `404` if you don't have an `index.html` file. I'll go stick one there so it's more obvious what's going on, but the URL is valid.

**Comment by bootc** [comment]
There should probably be an `index.html` in there... @RangerRick ?

You should do something like `helm repo add netbox https://charts.netbox.oss.netboxlabs.com` and it should be fine.

**Comment by RangerRick** [comment]
Yeah, I'm adding one now :)

**Comment by bootc** [comment]
Though it's probably worth noting the new repo only contains 5.0.0-beta* chart versions at the moment. For the 4.1.1 chart (which does still just work with NetBox 4.0) please use the old repo at https://charts.boo.tc.

**Comment by TheoBassaw** [comment]
I do see there is an index.yaml at the URL, but what confuses me the most is when I do add the repo as so with
```
helm repo add netbox https://charts.netbox.oss.netboxlabs.com
helm repo update
helm search repo netbox
```
I just get no results found. I will try the old repo

**Comment by RangerRick** [comment]
I believe for search to work, you need to add `--devel` to your cli, until we release 5.0 proper.

**Comment by bootc** [comment]
Ah, yes, because the new repo only has the beta chart:
```
$ helm search repo --devel netbox
NAME         	CHART VERSION	APP VERSION	DESCRIPTION                                       
bootc/netbox 	4.1.1        	v3.2.8     	IP address management (IPAM) and data center in...
netbox/netbox	5.0.0-beta.15	v4.0.0     	IP address management (IPAM) and data center in...
```

**Comment by TheoBassaw** [comment]
Ah I see, I missed that it's the develop branch by default

**Comment by TheoBassaw** [comment]
Thanks again, I got it going now.
