### ISSUE TITLE
Can't pull OCI chart

### ISSUE THREAD

**Issue by holmesb** [netbox-community/netbox-chart#252]
Hi,

When I try to [install ](https://github.com/netbox-community/netbox-chart?tab=readme-ov-file#netbox)this chart using:
`helm install netbox oci://ghcr.io/netbox-community/netbox-chart/netbox`
I get:
`Error: INSTALLATION FAILED: GET "https://ghcr.io/v2/netbox-community/netbox-chart/netbox/tags/list": GET "https://ghcr.io/token?scope=repository%3Anetbox-community%2Fnetbox-chart%2Fnetbox%3Apull&service=ghcr.io": unexpected status code 401: unauthorized: authentication required`

If I first login using my github PAT: `helm registry login ghcr.io`

the same command gives new error: `Error: INSTALLATION FAILED: GET "https://ghcr.io/v2/netbox-community/netbox-chart/netbox/tags/list": GET "https://ghcr.io/token?scope=repository%3Anetbox-community%2Fnetbox-chart%2Fnetbox%3Apull&service=ghcr.io": unexpected status code 403: denied: denied`

PAT has `read_package` permission, which I understand is required for private repos, but this is public, right?

Am I missing something?

Thanks

**Comment by LeoColomb** [comment]
@netbox-community/netbox-chart-admins Is it possible to configure the package with public visibility?

**Comment by siku4** [comment]
I had the same problem a few minutes ago. I then saw under [Deployments](https://github.com/netbox-community/netbox-chart/deployments) that the chart is also hosted via GitHub Pages. Use `https://charts.netbox.oss.netboxlabs.com` as repo url and it will work!

**Comment by holmesb** [comment]
I tried `helm repo add netbox https://charts.netbox.oss.netboxlabs.com`, but then `helm install netbox netbox/netbox` gives `Error: INSTALLATION FAILED: chart "netbox" matching  not found in netbox index. (try 'helm repo update'): no chart version found for netbox-`. Can anyone give a working `helm repo add` \ `helm install` commands?

**Comment by Zaunei** [comment]
On the subject of OCI: 

Is it possible to continue offering the `https://charts.netbox.oss.netboxlabs.com` repo in the future?

Depending on the tooling (in my case https://github.com/Qovery/helm-freeze), I currently find it much easier to use https than OCI repos. Locally with plain helm cli I have also run into [this](https://github.com/helm/helm/issues/11951) error. I have not yet had such problems with https repos.

Apart from that, I think it's great that OCI is also offered.


@holmesb Maybe this older README will help? https://github.com/netbox-community/netbox-chart/commit/0017458507e6aeac8728b6f57fa5972e76e43387

```
helm repo add netbox https://charts.netbox.oss.netboxlabs.com/
helm repo update
helm pull netbox/netbox --version 5.0.0-beta.34
```

At least it works for me.

**Comment by RangerRick** [comment]
Until 5.0.0 comes out, you need to add `--devel` to your helm pull. It should grab the latest beta then.

**Comment by RangerRick** [comment]
OK, I think we have the OCI permissions correct now, give it another shot.

**Comment by LeoColomb** [comment]
I confirm it works well. During the beta period, specifying the version is recommended, as `--devel` might not select the latest dev version.

```
helm install netbox oci://ghcr.io/netbox-community/netbox-chart/netbox --version 5.0.0-beta.34
```

**Comment by holmesb** [comment]
Yes OCI working now @RangerRick. So does:
```
helm repo add netbox https://charts.netbox.oss.netboxlabs.com/
helm repo update
helm install --devel netbox netbox/netbox
```

**Comment by davidusken** [comment]
> On the subject of OCI:
> 
> Is it possible to continue offering the `https://charts.netbox.oss.netboxlabs.com` repo in the future?
> 
> Depending on the tooling (in my case https://github.com/Qovery/helm-freeze), I currently find it much easier to use https than OCI repos. Locally with plain helm cli I have also run into [this](https://github.com/helm/helm/issues/11951) error. I have not yet had such problems with https repos.

Agreed, that would be great. Especially since ArgoCD still has somewhat limited support for OCI charts. I'm able to add it as a repository but not refer to it using the alias. With the https chart everything works flawlessly.

Some open tickets about this:
```
https://github.com/helm/helm/pull/11771
https://github.com/argoproj/argo-cd/issues/7436
https://github.com/argoproj/argo-cd/pull/18646
```

**Comment by LeoColomb** [comment]
While not promoted, the URL is still and will be kept updated. You can just use it.
