### ISSUE TITLE
Fix instructions for installing via helm

### ISSUE THREAD

**Issue by txj-xyz** [netbox-community/netbox-chart#264]
Essentially there is no proper instructions for installing this via `helm` inside of either Rancher or straight `helm` CLI, missing versions or mismatch named versions cause a failure of installation.

You also cannot add this repo via Rancher UI as it does not find any versions from the main repo URL

Related: #260

**Comment by doteater** [comment]
@txj-xyz what was the fix? I have this happening to me today when I run the "TLDR" command from the README with helm CLI. I don't understand what tech stand you're assuming for that command - what is "straight helm cli"?

**Comment by joelvdvoort** [comment]
@doteater I don't know if you managed to figure it out but you can get it going by passing the version string without the "netbox-" prefix. Example: helm pull oci://ghcr.io/netbox-community/netbox-chart/netbox --version 5.0.0-beta.61

Imho this should be made clear in the docs.
