### ISSUE TITLE
logic in conditional at top of secrets appears incorrect

### ISSUE THREAD

**Issue by ef-trss** [netbox-community/netbox-chart#270]
Title.

For example, in [redis-secret.yaml#L1](https://github.com/netbox-community/netbox-chart/blob/netbox-5.0.0-beta.44/charts/netbox/templates/redis-secret.yaml#L1), if I'm reading the logic correctly, it will cause the secret to NOT be created if either `redis.enabled` is true OR if both `*Redis.existingSecretName` keys have values defined.

| redis.enabled | tasksRedis.existingSecretName | cachingRedis.existingSecretName | RESULT |
| ------------- | ------------- | ------------- | ------------- |
| TRUE | set | set | FALSE |
| TRUE | set | unset | FALSE |
| TRUE | unset | set | FALSE |
| TRUE | unset | unset | FALSE |
| FALSE | set | set | FALSE |
| FALSE | set | unset | TRUE |
| FALSE | unset | set | TRUE |
| FALSE  | unset | unset | TRUE |

I believe the logic should be `if and .Values.redis.enabled (not (and .Values.tasksRedis.existingSecretName .Values.tasksRedis.existingSecretName))`

| redis.enabled | tasksRedis.existingSecretName | cachingRedis.existingSecretName | RESULT |
| ------------- | ------------- | ------------- | ------------- |
| TRUE | set | set | FALSE |
| TRUE | set | unset | TRUE |
| TRUE | unset | set | TRUE |
| TRUE | unset | unset | TRUE  |
| FALSE | set | set | FALSE |
| FALSE | set | unset | FALSE |
| FALSE | unset | set | FALSE |
| FALSE  | unset | unset | FALSE |

If redis.enabled is false, we don't need the secret at all, and if both existingSecretName values are set, then the secret will be blank.

----

postgres-secret.yaml has a similar problem, albeit a simpler case.

Currently: `if not (or .Values.postgresql.enabled  .Values.externalDatabase.existingSecretName)`
Suggested: `if and .Values.postgresql.enabled  (not .Values.externalDatabase.existingSecretName)`

----

Happy to open a PR if you agree!  I have several other small things that I found as well, but this one seemed to warrant an explanation first.

**Comment by RangerRick** [comment]
Your logic makes sense to me, I would totally appreciate a PR if you've got the chance. Thanks!

**Comment by fletch3555** [comment]
Closing per my comment in #275
