### ISSUE TITLE
Issues with LDAP Deployment

### ISSUE THREAD

**Issue by crobbinsviasat** [netbox-community/netbox-chart#284]
Not sure if this belongs here or under the netbox project.  When implementing LDAP, I get the following errors in the pod logs -

```
2024/07/18 16:48:55 [info] 104#131 *21 send(35, 7FC66F600000, 3065) failed (32: Broken pipe)
2024/07/18 16:48:58 [info] 104#131 *22 send(37, 7FC66EBFF000, 3065) failed (32: Broken pipe)
```

The web frontend will hang and return "Connection Reset".  I've followed the fix in  [this issue](https://github.com/netbox-community/netbox-chart/issues/174) which enabled LDAP config and get the same result.  Additionally, I've deployed an Ubuntu pod with LDAP tools and validated that the cluster can reach and query/bind to the LDAP server with the credentials I am using with netbox.  Is there better guidance for LDAP configuration I should be following?

**Comment by RangerRick** [comment]
FYI, this is a thing I intend to spend some time looking into, but I don't want to block 5.0.0 on it, since we're close to having something releasable, and 4.1.1 is so out-of-date.
