### ISSUE TITLE
nodeSelector not properly indented in deployment.

### ISSUE THREAD

**Issue by mglazenborg** [netbox-community/netbox-chart#297]
In #285 the indentation of nodeSelector was changed to 6 from 8. 

This results in the following YAML:
```yaml
nodeSelector:
kubernetes.io/os: linux
```
Rather than the properly formatted:
```yaml
nodeSelector:
  kubernetes.io/os: linux
```

This change was also done to affinity, but I've not tested if this also occurs there.

**Comment by LeoColomb** [comment]
Good catch, thanks.
I'm actually already working on a change set to fix all these indentations issues.
