### ISSUE TITLE
Netbox pod crashing

### ISSUE THREAD

**Issue by tbartschat** [netbox-community/netbox-chart#315]
**General settings**

Kubernetes Version: v1.30.0
OS Version: Ubuntu 22.04.4 LTS
Netbox Helm Chart Version: 5.0.0-beta.78
Netbox appVersion: v4.0.9

[values.txt](https://github.com/user-attachments/files/16709005/values.txt)

In some cases the netbox pod is crashing. Let me describe two cases.

**1st case**

While running python import scripts in background (one by one, no bulk create) and parallel editing device status or anything else via Webgui (on different device), the pod chrashed and restarts. 
 
Python VENV: 3.10.12
pynetbox: 7.3.4

**2nd case**

When I want to delete many devices (approx 400) via WebGui and performing a bulk delete request the netbox pod is also crashing.
Service is not given and after the crash the devices are not deleted.

I already tried with to deploy 2 netbox pods running but the result is the same.

Any ideas or suggestions here what to do?

**Comment by LeoColomb** [comment]
Thanks for opening this issue @tbartschat.
To investigate, would you mind:
* Uploading your `values.yaml` into a gist instead https://gist.github.com/
* Providing the crashed pod logs
* Providing the pod's events history.

**Comment by LeoColomb** [comment]
Discussion moved to #316
