### ISSUE TITLE
Cloning projects from Gitlab via SSH fails

### ISSUE THREAD

**Issue by moppmans** [netbox-community/netbox-chart#321]
Hey all...

can anyone tell me which public ssh key from which pod I should use for cloning gitlab projects as datasources? 

![image](https://github.com/user-attachments/assets/3fcda036-be80-4508-90c1-3319d7c96002)

Thanks!

BG Matthias

**Comment by LeoColomb** [comment]
Thanks for opening this issue @moppmans.
That being said, I don't see any link with Netbox chart and the repository you're reporting this issue to.
Based on the very little information provided, I'm closing the ticket.

**Comment by LeoColomb** [comment]
Duplicated into #322
