### ISSUE TITLE
Failing after splitting python files from ConfigMap

### ISSUE THREAD

**Issue by devasmith** [netbox-community/netbox-chart#340]
Hi,

I noticed that when upgrading Netbox helmrelease to `netbox@5.0.0-beta.90` I got the following error message:

```
    message: 'Helm upgrade failed for release netbox/netbox with chart netbox@5.0.0-beta.90:
      template: netbox/templates/worker-deployment.yaml:28:28: executing "netbox/templates/worker-deployment.yaml"
      at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling
      include: template: netbox/templates/configmap.yaml:170:13: executing "netbox/templates/configmap.yaml"
      at <.Files.Get>: can''t evaluate field Files in type interface {}'
```

Can this be related to this PR? https://github.com/netbox-community/netbox-chart/pull/327

**Comment by LeoColomb** [comment]
Thanks for opening this issue.
Indeed, and a fix is already under its way: [`f7536eb` (#329)](https://github.com/netbox-community/netbox-chart/pull/329/commits/f7536eb25d01501f00a2776f57ffdc498e06d7e5)
