### ISSUE TITLE
Invalid header in gzip format

### ISSUE THREAD

**Issue by rhizoet** [netbox-community/netbox-chart#356]
We deploy netbox with flux and an OCI repository. flux requires a tar+gzip file to unpack the files correctly: https://fluxcd.io/flux/components/source/ocirepositories/#layer-selector

I have seen that the last 4 version still has `tar.gz`. However, the current beta versions do not. Can `tar.gz` be uploaded there as well, please, so that flux can work with it?

**Comment by rhizoet** [comment]
Forget it again. I was looking the wrong way.

**Comment by LeoColomb** [comment]
Thanks for opening this issue @rhizoet. 
The OCI registry already follows all requirements by standards. 
In fact, I personally use FluxCD as well and everything is working as expected. 

Can you please provide the log of the integration?

**Comment by rhizoet** [comment]
For sure, here we go:

`failed to extract layer contents from artifact: requires gzip-compressed body: gzip: invalid header `

**Comment by LeoColomb** [comment]
> Forget it again. I was looking the wrong way.

I'm confused, have you found the problem?

**Comment by rhizoet** [comment]
Sorry, I don't have found the problem yet. Do you have a clue, what the error can be?

**Comment by LeoColomb** [comment]
What are the version of everything?
* Netbox chart
* FluxCD
* Kubernetes

**Comment by rhizoet** [comment]
Ok, the problem has been solved. I had mistakenly used `OCIRepository` instead of a `HelmRepository` with `type: “oci”`. As a result, it couldn't pull anything and the error occurred.

Now that I have changed it, the process continues.

Sorry for the false alarm :D
