### ISSUE TITLE
Syncing LDAP groups with Django

### ISSUE THREAD

**Issue by Denis-themenace** [netbox-community/netbox-chart#360]
Hi All! 

I would like to know if it is possible to synchronize only specific groups from LDAP to Django? 
According to [Django documentation](https://django-auth-ldap.readthedocs.io/en/latest/reference.html#auth-ldap-mirror-groups) it can be done via AUTH_LDAP_MIRROR_GROUPS, as the documentation states the following: 
_**"This can also be a list or other collection of group names, in which case we’ll only mirror those groups and leave the rest alone."**_

Could you please tell if this functionality has already been implemented or not? 

I've tried to add a list of group names, but it doesn't work:
```
findGroupPerms: true
mirrorGroups: ['group1', 'group2']
mirrorGroupsExcept: null
```
I'm currently using:
Chart: netbox-5.0.0-beta.103
Netbox: v4.1.1-3.0.2

Thanks!

**Comment by LeoColomb** [comment]
Thanks for filing this issue, @Denis-themenace.
That being said, it has nothing related to the chart.
As explained by the documentation page you linked, `AUTH_LDAP_MIRROR_GROUPS` (thus `mirrorGroups`) is a boolean value (only `true` or `false`).

**Comment by Denis-themenace** [comment]
Thanks for the info Leo @LeoColomb 

For those who will also be looking for an answer to this question. This feature is working if there is no spaces between the group names:

mirrorGroups: ['group1','group2',group*’]

Once user logs into Netbox via LDAP, Django will automatically create/mirror only those groups that are mentioned in the list above and will add this user as a member of this new group(s). All new users will also be placed in the groups they belong to.
