### ISSUE TITLE
Helm install failes to fetch token (403 error)

### ISSUE THREAD

**Issue by djryanj** [netbox-community/netbox-chart#363]
When trying to install the chart, the following error is received:

```pwsh
PS > helm install --dry-run netbox --devel oci://ghcr.io/netbox-community/netbox-chart/netbox
Error: INSTALLATION FAILED: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Anetbox-community%2Fnetbox-chart%2Fnetbox%3Apull&scope=repository%3Auser%2Fimage%3Apull&service=ghcr.io: 403 Forbidden
```

Note: I recognize this may not be a netbox problem specifically; however, as I cannot find whether or not it _should_ be available anonymously or if the chart **requires** login to pull, at the very least if login is required then an update to the documentation stating that would be grand.

**Comment by LeoColomb** [comment]
Thanks for filing this issue, @djryanj.
That being said, I cannot reproduce
Also, as you are noting, this would not be related to NetBox or its chart.
The only recommendation I can provide is eventually to try with the version arg instead of the devel arg:
```shell
helm install --dry-run netbox --version 5.0.0-beta.108 oci://ghcr.io/netbox-community/netbox-chart/netbox
```

**Comment by djryanj** [comment]
@LeoColomb I tried as suggested and got the same result. Not sure what's going on, I'll report back if I discover something.
