### ISSUE TITLE
Netbox connot read the ssl certs that was generated by cert manager

### ISSUE THREAD

**Issue by Teskoh27** [netbox-community/netbox-chart#378]
I'm trying to run netbox in openshift, but I cannot get netbox to read my certificates even though I've had them mounted as a secret in /etc/ssl/certs.

I changed the image to run as a regular user.  

Can someone help?

**Comment by LeoColomb** [comment]
Thanks for filing this issue, @Teskoh27. 
We have updated our issue template to help us on providing support efficiently. 
Would you mind creating a new issue with that same case? 
Thanks
