### ISSUE TITLE
Provide "helm repo index / index.xaml" for netbox helm repository

### ISSUE THREAD

**Issue by Delta1977** [netbox-community/netbox-chart#395]
### Proposed functionality

as a good Practise : 
Please provide a Repositoy index for this Helm repository.

[Manual for setting up](https://nakamasato.medium.com/lets-set-up-your-own-helm-chart-repo-and-start-publishing-charts-9d89d259986c)

### Use case

Helm Repo with an repoindex is very usefull :

**Comment by LeoColomb** [comment]
Thanks for filing this issue, @Delta1977.
That said, a Helm repository is already available at `https://charts.netbox.oss.netboxlabs.com/`.
It is not promoted as the actual good practice nowadays is to use [OCI registries](https://helm.sh/docs/topics/registries/).

**Comment by Delta1977** [comment]
thanks for the quick answer. the link is enough for me

**Comment by Delta1977** [comment]
@LeoColomb who is the maintainer from "https://charts.netbox.oss.netboxlabs.com/" ? 
Normaly i can use placeholder for Versions in Helm-applications like Argocd for repos like Bitnami.
in example if i select 5.0.0-beta* or 5.0.0-beta.x then argocd pulls automaticly the latest beta...
But for the netbox-repo it didnt work. 
Seams the netbox versioning is not SemVer2 compatible.

**Comment by LeoColomb** [comment]
This Helm repository is part of this git repo.
It is semantic versioning, but beta versions are not part of semantic versioning schema per se.
But beta versions obviously not being stable versions, this behavior is somewhat quite expected.
In any case, again, OCI registry is more the way to go.
