### ISSUE TITLE
Chart contains references to raw.githubusercontent.com which prevents air-grapped installations

### ISSUE THREAD

**Issue by ErikLundJensen** [netbox-community/netbox-chart#409]
### Proposed functionality

The values.schema.json contains references to source outside of the chart. When deploying the chart in an air-gapped environment there should be no external dependencies.

> Error: values don't meet the specifications of the schema(s) in the following chart(s): netbox: Get "https://raw.githubusercontent.com/bitnami/charts/master/bitnami/postgresql/values.schema.json": dial tcp 185.199.108.133:443: i/o timeout

There are two references in values.schema.json:
```
"allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/bitnami/charts/master/bitnami/postgresql/values.schema.json"
        },
```

```
     "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/bitnami/charts/master/bitnami/redis/values.schema.json"
        },
```

### Use case

Support air-gapped installation. Improves security as unknown content is not downloaded during installation.

**Comment by LeoColomb** [comment]
Thanks for filing this issue, @ErikLundJensen. 
Simply use the option `--skip-schema-validation` when using Helm [install](https://helm.sh/docs/helm/helm_install/#options)/upgrade command.
