### ISSUE TITLE
Enabling extraConfig fails with cronjob.yaml: line 78: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by papanito** [netbox-community/netbox-chart#410]
### The Helm chart version

netbox-5.0.0-beta.128

### Environment Versions

```text
Kubernetes 1.30
```

### Custom chart values

```yaml
# https://github.com/netbox-community/netbox-chart/blob/develop/docs/auth.md
remoteAuth:
  enabled: true
  backends:
    - social_core.backends.azuread.AzureADOAuth2
extraConfig:
  - secret:
      secretName: netbox-sso
```

### Current Behavior & Steps to Reproduce

I follow [this guide](https://github.com/netbox-community/netbox-chart/blob/develop/docs/auth.md) to enable oauth with Azure. However as soon as I add `extraConfig` I get the following error

```
helm template remote/netbox --version 5.0.0-beta.128 -f values.yaml > netbox.tmp.yaml 
Error: YAML parse error on netbox/templates/cronjob.yaml: error converting YAML to JSON: yaml: line 78: mapping values are not allowed in this context

Use --debug flag to render out invalid YAML
```

### Expected Behavior

Templating of helm chart goes without error

**Comment by LeoColomb** [comment]
Thanks for filing this issue, @papanito.
The YAML structure of your values is not valid, indentation is key.

> ```diff
>   - secret:
> -   secretName: netbox-sso
> +      secretName: netbox-sso
> ```

**Comment by papanito** [comment]
copy and paste error, even so the indentation is correct, the error is still valid.

**Comment by LeoColomb** [comment]
I see, versions before 5.0.0-beta.130 were buggy on extra config rendering.
Can you try with a more recent version?
[Latest is 5.0.0-beta.141](https://github.com/netbox-community/netbox-chart/releases).

**Comment by papanito** [comment]
Thanks, yes with `beta.141` the issue is not reproducible
