### ISSUE TITLE
extraConfig and SOCIAL_AUTH_PIPELINE generates: error converting YAML to JSON: yaml: line 303: could not find expected ':' 

### ISSUE THREAD

**Issue by papanito** [netbox-community/netbox-chart#411]
### The Helm chart version

netbox-5.0.0-beta.141

### Environment Versions

```text
Kubernetes 1.30
```

### Custom chart values

```yaml
# https://github.com/netbox-community/netbox-chart/blob/develop/docs/auth.md
remoteAuth:
  enabled: true
  backends:
    - social_core.backends.azuread.AzureADOAuth2
extraConfig:
  - secret:
      secretName: netbox-sso
  - values:
      SOCIAL_AUTH_PIPELINE: 
      [
        "social_core.pipeline.social_auth.social_details",
        "social_core.pipeline.social_auth.social_uid",
        "social_core.pipeline.social_auth.social_user",
        "social_core.pipeline.user.get_username",
        "social_core.pipeline.social_auth.associate_by_email",
        "social_core.pipeline.user.create_user",
        "social_core.pipeline.social_auth.associate_user",
        "netbox.authentication.user_default_groups_handler",
        "social_core.pipeline.social_auth.load_extra_data",
        "social_core.pipeline.user.user_details",
        "netbox.sso_pipeline_roles.set_role",
      ]
```

### Current Behavior & Steps to Reproduce

I follow [this guide](https://github.com/netbox-community/netbox-chart/blob/develop/docs/auth.md) to enable oauth with Azure. However as soon as I add `extraConfig` I get the following error

```
helm template remote/netbox --version 5.0.0-beta.141 -f values.yaml > netbox.tmp.yaml
Error: failed to parse values.yaml: error converting YAML to JSON: yaml: line 303: could not find expected ':'
```

### Expected Behavior

Templating of helm chart goes without error

**Comment by LeoColomb** [comment]
Thanks for filing this issue, @papanito.
That being said, again, indentation is important in YAML file.
Please review your values.

**Comment by papanito** [comment]
> That being said, again, indentation is important in YAML file.
I know, just did not catch it, now I see it . Sorry for filing the issue

**Comment by ALL-SPACE-Anas** [comment]
Hi @papanito, can you please share an updated link to this document that shared configuration for azure ad oauth? The current link doesn't work unfortunately.

Thanks in advance,
